#pragma once
#pragma comment(lib, "gdiplus.lib")
#pragma comment(lib,"user32.lib")

#include <queue>
#include <functional>
#include <set>
#include <windows.h>
#include <vector>
#include <memory>
#include <tuple>
#include <ctime>
#include <future>
#include <thread>
#include <queue>
#include <cstdlib>
#include <random>
#include <gdiplus.h>
#include <objidl.h>
#include <algorithm>
#include <stdio.h>
#include <chrono>
#include <fstream>
#include <boost/ptr_container/indirect_fun.hpp>
#include <gsl/gsl>
#include "PrintInGDIplusWindow.h"
#include "vertex.h"
